### PR TITLE
Create Cookie

### PR DESCRIPTION
**Pull request by Cohennnnnnn**

### CODE REVIEW

**Comment by 4xx404** [comment]
@Cohennnnnnn what's different in this pull request? 'Cookie' file is an identical copy of dashboard & doesn't look to be included anywhere?

**Comment by Cohennnnnnn** [comment]
IK THATS THE JOKE

**Comment by 4xx404** [comment]
@Cohennnnnnn ???

**Comment by Cohennnnnnn** [comment]
Congratulations!

**Pull request closed without merging**
